# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eafc32efd24b4d4357fad2550b068d033cd42f1a90f23881769fa72da328bcae5eba30265c2f332c9c1f7f7375d93b29f9239ee6aa58399c9ef02f0c07ed7277

test:
  secret_key_base: a01a78ff64936f67a678d783f94d341823396e23a7e66d440fb23412eea0ca90e60530f7929e5f2e1f0565f9ced1ff2c8d1d2cb634edbe94faef8d6a1e892cf9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
